// Novedades de la agenda, de la más reciente a la más antigua. Cada cambio visible para el equipo suma una entrada acá,
// en el mismo cambio que lo introduce (junto con su sección de la ayuda). La más nueva enciende el puntito del menú de Ayuda.
import type { Rol } from '@/lib/ayuda/temas'

// `banner`: la novedad se anuncia además con un banner arriba de la pantalla para los roles de `para`, hasta que se cierra o pasa `hasta`
// (inclusive). El botón lleva al tema `tema` de la ayuda.
export type BannerNovedad = { para: Rol[], texto: string, corto: string, tema: string, hasta: string }
export type Novedad = { fecha: string, titulo: string, texto: string, para?: Rol[], banner?: BannerNovedad }

export const NOVEDADES: Novedad[] = [
  { fecha: '2026-10-06', titulo: 'Excel de Mis escuelas con los próximos cronogramas', texto: 'El Excel de Mis escuelas suma una columna con los próximos cronogramas de cada escuela (la ventana de fechas y el tipo, uno por renglón), para tener todo junto al comparar con tu registro.' },
  { fecha: '2026-10-06', titulo: 'Mis escuelas: buscador grande, lista y Excel', texto: 'En Mis escuelas el buscador pasó al primer plano (con una ✕ para borrar lo escrito) y ahora busca también por dirección y por contacto. Hay una vista en Lista con escuela, CUE, dirección, localidad, distrito y contacto (con teléfono y correo para llamar o escribir), con columnas que se ordenan, además de las tarjetas. El botón Excel descarga la lista tal como la ves, para comparar con tu registro propio.' },
  { fecha: '2026-10-06', titulo: 'Botón Volver en el celular', texto: 'En el celular, Mis escuelas, Cronogramas y el Registro de reclamos tienen arriba un botón Volver que te lleva a la pantalla de la que venías (el Tablero, tu agenda u otra sección), sin pasar por la barra de abajo.' },
  { fecha: '2026-10-06', titulo: 'Accesos rápidos en el Tablero', texto: 'Arriba del Tablero hay tres tarjetas con un número: Mis escuelas (cuántas tenés y cuántas con reclamo abierto), Mis reclamos (abiertos en tus escuelas) y Cronogramas (próximos en tus escuelas). Un toque y entrás directo; siguen estando también en el menú de las iniciales. El CED ve los números de todo el equipo.' },
  { fecha: '2026-10-06', titulo: 'Marcá como resuelto los reclamos de tus escuelas', texto: 'En el registro de reclamos, el FED a cargo de una escuela puede tocar Marcar resuelto en un reclamo abierto, con una nota opcional (por ejemplo, "la escuela confirmó que ya funciona"). No se avisa a nadie y en la tarjeta queda quién lo marcó. El filtro Solo los míos ahora incluye los reclamos de tus escuelas. El CED sigue anotando los números y los demás estados.' },
  { fecha: '2026-10-06', titulo: 'Cronogramas: programa, vigencia y guía para el CED', texto: 'Cada cronograma indica si es de Educar o de PBA y si es una reprogramación. Al abrirlo, Para tener en cuenta muestra la vigencia (de 7 a 10 días desde las fechas), si la escuela tiene turno vespertino y si comparte predio con otra. El CED ve además los pasos de la guía como referencia: contacto de los directivos en PBA (con la fecha límite), domicilio, aviso al establecimiento y estado en la planilla.' },
  { fecha: '2026-10-06', titulo: 'Mensaje a la escuela: solo informa el cronograma', texto: 'El mensaje de Armar mensaje en Cronogramas ahora solo informa el cronograma de conectividad previsto (escuela, tarea, fecha, empresa y responsable), sin pedir cambios de fecha, porque los cronogramas ya vienen establecidos. El responsable sale ordenado (por ejemplo, "Cañete Zenteno") y el DNI va sin puntos.' },
  { fecha: '2026-10-06', titulo: 'Cronogramas: avisá a la escuela con el mensaje armado', texto: 'En cada cronograma, Armar mensaje prepara el aviso informativo para el directivo (tarea, fecha, empresa y responsable) y muestra los contactos de la escuela: lo copiás o lo abrís en tu correo. Después anotás Escuela avisada (el FED a cargo) y, si sos el CED, Jefatura avisada; cuando el CED avisa a la jefatura, el FED recibe una notificación. Hay filtros para ver las visitas con la escuela o la jefatura sin avisar.' },
  { fecha: '2026-10-06', titulo: 'Buscador de escuelas más preciso', texto: 'Al buscar con una sigla y un número, el buscador trae solo lo que pediste: "ees 1" ya no mezcla las técnicas ni las agrarias N° 1, y "ep 4 berisso" suma el distrito para afinar. También entiende más siglas (CENS, CEC, CEF, ISFD, ISFT, EESA y otras). Las extensiones de la escuela pedida salen al final.' },
  { fecha: '2026-10-06', titulo: 'Mis escuelas', texto: 'En el menú de las iniciales, Mis escuelas lista las escuelas que tenés a cargo, con buscador y filtros por distrito y nivel. Cada tarjeta muestra el próximo cronograma, los reclamos abiertos, la próxima acción y la última visita; al tocarla se abre la ficha completa, con conectividad, reclamos, cronogramas y contactos. El CED y la administración ven todas las escuelas, con filtro por FED.' },
  { fecha: '2026-10-06', titulo: 'Cronogramas: anotá cómo salió y recibí avisos', texto: 'En Cronogramas (menú de las iniciales) cada FED ve los cronogramas de sus escuelas y puede anotar si se realizó, no se realizó o se reprogramó (con el motivo); el CED lo ve y recibe un aviso. Cuando aparecen cronogramas nuevos y el día hábil anterior al comienzo, te llega un solo aviso con los de tus escuelas, y el CED recibe un resumen.', banner: { para: ['fed', 'ced'], texto: '¡Novedad! Cronogramas: mirá los de tus escuelas, anotá cómo salieron y recibí avisos agrupados', corto: '¡Novedad! Cronogramas de las escuelas', tema: 'cronogramas', hasta: '2026-10-20' } },
  { fecha: '2026-10-06', titulo: 'Cronogramas en la agenda', texto: 'En el menú de las iniciales, Cronogramas muestra los cronogramas de conectividad de las escuelas (reparaciones, instalaciones, certificaciones), leídos del consolidado de conectividad: ventana de fechas, tipo, proveedor, instaladores y FED a cargo. Se actualiza sola cada madrugada. Por ahora es solo lectura.', para: ['ced'] },
  { fecha: '2026-10-06', titulo: 'Recordatorios de PVE más precisos', texto: 'Si subís tu PVE a la carpeta el mismo día en que sale el recordatorio, la agenda la registra antes de avisar y ya no te llega el aviso de algo que entregaste.', para: ['fed'] },
  { fecha: '2026-10-06', titulo: 'Enlaces de reuniones más fáciles de cargar', texto: 'Al agendar una reunión virtual o híbrida podés pegar la dirección con o sin https://, o todo el texto de la invitación de Meet o Zoom: la agenda toma solo el enlace de la videollamada. Ya no aparece el cartel del navegador "Ingresa una URL".' },
  { fecha: '2026-10-05', titulo: 'Las novedades importantes, en un banner', texto: 'Cuando hay una novedad importante, la agenda la anuncia con un banner celeste arriba de la pantalla, con un botón que te lleva al tema de la ayuda (cada perfil ve la novedad que le corresponde). Se va cuando lo cerrás o a los pocos días, y las novedades siguen en la pestaña Novedades de la ayuda.' },
  { fecha: '2026-10-05', titulo: 'Avisos de reclamos también como banner', texto: 'Cuando un FED registra un reclamo de conectividad, al CED le llega una notificación. Los avisos de reclamos (reclamo nuevo para el CED; número de ticket o resolución para el FED) aparecen además como banner arriba de la pantalla, con el botón Ver registro. Si llegan varios, quedan juntos en un solo banner.' },
  { fecha: '2026-10-04', titulo: 'Agenda del equipo: territorio según la etiqueta', texto: 'En la vista En territorio, la Oficina R1 cuenta siempre (funciona en la EES 31, aunque se cargue con la DTE como sede) y la Asistencia remota nunca cuenta, porque es virtual. En una visita con varias etiquetas alcanza con que una cuente.', para: ['ced'] },
  { fecha: '2026-10-04', titulo: 'Número de encuentro más preciso', texto: 'Al numerar el próximo encuentro de un club o grupo de prácticas, ahora cuentan también las fechas marcadas como realizadas aunque no se hayan completado los datos del encuentro. Si una fecha quedó como realizada sin que hubiera encuentro, pasala a cancelada para que no corra la numeración.', para: ['fed'] },
  { fecha: '2026-10-04', titulo: 'PEAT: la escuela del encuentro a la vista', texto: 'Las tarjetas de los grupos de prácticas muestran, debajo del curso y el grupo, la escuela donde es el encuentro y su localidad. En el detalle, la escuela aparece con su nombre completo, además del CUE.', para: ['fed'] },
  { fecha: '2026-10-03', titulo: 'Contadores del registro de reclamos más parejos', texto: 'En el celular, los tres contadores del registro de reclamos tienen el mismo tamaño y los nombres van en plural: Reclamos enviados, En proceso y Resueltos.' },
  { fecha: '2026-10-02', titulo: 'Buscador de escuela: la lupa en su lugar', texto: 'En el buscador de escuela del reclamo, la lupa ya no se corre al abrir los resultados: queda siempre dentro del campo.' },
  { fecha: '2026-10-02', titulo: 'Reclamos con Gmail directo y menú ordenado', texto: 'En el celular, Abrir en mi correo ahora abre la app de Gmail con el mensaje ya armado, sin pasar por el navegador. Si no tenés la app, se abre en el navegador como antes. Además, el botón Cancelar se ve más claro y el menú de las iniciales quedó agrupado: lo tuyo, conectividad, coordinación (si sos administración) y el resto, con Cerrar sesión al final.' },
  { fecha: '2026-10-02', titulo: 'Estados del registro de reclamos con colores más claros', texto: 'En el registro de reclamos, Reclamo enviado, En proceso y Resuelto ahora se distinguen de un vistazo: ámbar, azul y verde, tanto en los contadores como en cada tarjeta.' },
  { fecha: '2026-10-02', titulo: 'Buscador de escuela en el reclamo', texto: 'Al armar un reclamo de conectividad, los resultados de la búsqueda de la escuela ahora se ven completos en el celular y en la compu, sin cortarse.' },
  { fecha: '2026-10-02', titulo: 'Avisos y Excel en el registro de reclamos', texto: 'Cuando el CED anota el número de ticket o de incidencia de tu reclamo, o lo marca resuelto, te llega una notificación (al tocarla se abre el registro). Además, el botón Excel del registro descarga la lista con tus filtros, con las mismas columnas de la planilla del CED.' },
  { fecha: '2026-10-02', titulo: 'Registro de reclamos de conectividad', texto: 'Al armar un reclamo y mandarlo al CED, tocá Reclamo enviado para registrarlo. En el menú de las iniciales, Registro de reclamos muestra los del equipo con su estado y el número de ticket o de incidencia que anota el CED cuando llega de Nivel Central. Si la escuela ya tiene un reclamo abierto, la agenda te avisa para seguir esa cadena.', banner: { para: ['ced'], texto: '¡Novedad! Los reclamos de conectividad que arman los FED llegan al registro: anotá el número de ticket o de incidencia y marcalos como resueltos desde ahí', corto: '¡Novedad! Reclamos de los FED en el registro', tema: 'registro-reclamos', hasta: '2026-10-19' } },
  { fecha: '2026-10-02', titulo: 'Reclamos de conectividad: mensaje al CED y tu correo oficial', texto: 'El reclamo ahora está redactado para el CED, con el saludo según la hora, el contacto de la escuela con su cargo uno por renglón y sin firma. Se abre en Gmail con tu cuenta institucional y tiene botón Cancelar. Además, el logo y el título de la agenda te llevan siempre al inicio.' },
  { fecha: '2026-10-02', titulo: 'Reclamos de conectividad armados por la agenda', texto: 'Desde el menú de las iniciales, la ficha de una escuela o una acción de Conectividad podés armar el reclamo: la agenda toma el enlace y el piso de la escuela, arma el asunto con el formato de la guía y el cuerpo del mail, y te dice qué adjuntar (checklist, foto del módem, plano). Después lo copiás o lo abrís en Gmail.', banner: { para: ['fed'], texto: '¡Novedad! Ahora podés armar tus reclamos de conectividad desde la agenda', corto: '¡Novedad! Reclamos de conectividad en la agenda', tema: 'reclamos', hasta: '2026-10-19' } },
  { fecha: '2026-10-02', titulo: 'Carpetas de fotos de PEAT con curso y grupo', texto: 'Las carpetas de fotos de los grupos de prácticas se nombran solo con el curso y el grupo, sin la escuela del encuentro. Las existentes se renombran solas en el próximo orden nocturno, o al tocar Ordenar ahora.', para: ['fed'] },
  { fecha: '2026-10-02', titulo: 'PEAT en la agenda: solo curso y grupo', texto: 'Las tarjetas de los grupos de prácticas muestran solo el curso y el grupo (por ejemplo, 7° Informática - Grupo 1), sin la escuela del encuentro. El detalle de la acción sigue indicando dónde fue.', para: ['fed'] },
  { fecha: '2026-10-02', titulo: 'Los grupos de PEAT se identifican por su escuela de origen', texto: 'Un grupo de prácticas ya no queda atado a una sede: se muestra con la escuela de origen de los estudiantes y cada encuentro lleva el lugar donde se hizo. Al crear un grupo nuevo, la escuela de origen es obligatoria.', para: ['fed'] },
  { fecha: '2026-10-02', titulo: 'Informe del período más compacto', texto: 'Los indicadores del informe ocupan menos lugar y el panel se puede plegar con la flecha del título: queda una línea con lo principal y los botones de Excel y PDF a la vista. La app recuerda cómo lo dejaste.' },
  { fecha: '2026-10-02', titulo: 'La cámara solo marca las acciones con fotos', texto: 'Si todas las fotos del día ya quedaron asignadas a otras acciones por horario, las acciones sin fotos dejan de mostrar la cámara. Solo la muestran si quedaron fotos del día sin asignar.', para: ['fed'] },
  { fecha: '2026-10-02', titulo: 'Acceso al sitio DTE Región 1', texto: 'En el menú de las iniciales sumamos Sitio DTE Región 1: abre el sitio de la Dirección en una pestaña nueva, con tu cuenta institucional.' },
  { fecha: '2026-10-01', titulo: 'Buscador de escuelas', texto: 'Con la lupa de arriba buscás cualquier escuela por nombre, sigla o CUE y ves su ficha: datos en tarjetas de color, próximas acciones, clubes y prácticas, y el historial de lo que se hizo ahí. Desde la ficha podés agendar una acción con la escuela ya elegida.' },
  { fecha: '2026-10-01', titulo: 'Más movimiento, siempre suave', texto: 'Los números del tablero suben hasta su valor, las barras crecen, el banner de avisos se desliza al aparecer, la campanita se sacude una vez cuando llega algo nuevo y las pantallas que cargan muestran un brillo suave. Con "reducir movimiento" activado en tu dispositivo, todo aparece quieto.' },
  { fecha: '2026-10-01', titulo: 'Acciones acompañadas en tu informe', texto: 'Tu informe del período muestra aparte las acciones de otros integrantes en las que te etiquetaron y que se realizaron. No se suman a tus totales, no cuentan las que rechazaste y también salen en el Excel y el PDF.' },
  { fecha: '2026-10-01', titulo: 'Los paros se registran como realizados', texto: 'Al agendar un día como Paro queda directamente como realizado, aunque la fecha todavía no haya llegado. Igual podés editarlo. Además, el banner de avisos ahora ocupa menos lugar en el celular.' },
  { fecha: '2026-10-01', titulo: 'Una agenda que se mueve con suavidad', texto: 'Las pantallas y las listas entran con un fundido corto, al marcar una acción como realizada se dibuja una tilde, lo que acabás de guardar se destaca un instante y los desplegables abren y cierran sin saltos. Si tenés activado "reducir movimiento" en tu dispositivo, no se anima nada.' },
  { fecha: '2026-10-01', titulo: 'Ayuda dentro de la agenda', texto: 'Desde el menú de las iniciales › Ayuda encontrás el manual completo, con buscador, siempre al día con la versión de la agenda. Acá mismo vas a ver cada novedad.' },
  { fecha: '2026-10-01', titulo: 'Avisos con color y banner', texto: 'Las notificaciones se distinguen por color (rojo: urgente, amarillo: aviso, verde: confirmación). Lo que pide una acción tuya, como la PVE, aparece además como banner arriba de la pantalla.' },
  { fecha: '2026-10-01', titulo: 'Cargar acciones pasadas no avisa a tus compañeros', texto: 'Al etiquetar o modificar acciones de fechas anteriores a hoy ya no se envía notificación: podés cargar todo junto a fin de mes sin molestar.' },
  { fecha: '2026-10-01', titulo: 'Clubes y talleres más ágiles', texto: 'Propuesta y destinatarios se eligen de una lista, los inscriptos se precargan con los del primer encuentro, el número de encuentro se calcula con los realizados y, al completar los datos de un encuentro, ya no se pregunta por "este y los siguientes".' },
  { fecha: '2026-10-01', titulo: 'Prácticas por curso', texto: 'Si un curso se dividió en grupos, cargá cada grupo en el campo Grupo: en las métricas de prácticas cuenta como un solo curso.', para: ['fed'] },
  { fecha: '2026-10-01', titulo: 'Agenda del equipo: "En territorio"', texto: 'La oficina R1 y las reuniones presenciales dentro de una escuela ahora cuentan como en territorio.', para: ['ced'] },
]

export const ultimaNovedad = (rol: Rol): string | null => NOVEDADES.find(n => !n.para || n.para.includes(rol))?.fecha ?? null

// Id de una novedad con banner (para recordar cuáles se cerraron).
export const idBanner = (n: Pick<Novedad, 'fecha' | 'titulo'>) => `${n.fecha}|${n.titulo}`

// Banner de novedad a mostrar: el de la novedad más reciente con banner para el rol, vigente hoy y que no se cerró.
export function bannerVigente(rol: Rol, hoy: string, cerrados: readonly string[]): { id: string } & BannerNovedad | null {
  const n = NOVEDADES.find(x => x.banner && x.banner.para.includes(rol) && hoy <= x.banner.hasta && !cerrados.includes(idBanner(x)))
  return n?.banner ? { id: idBanner(n), ...n.banner } : null
}
