// Novedades de la agenda, de la más reciente a la más antigua. Cada cambio visible para el equipo suma una entrada acá,
// en el mismo cambio que lo introduce (junto con su sección de la ayuda). La más nueva enciende el puntito del menú de Ayuda.
import type { Rol } from '@/lib/ayuda/temas'

// `banner`: la novedad se anuncia además con un banner arriba de la pantalla para los roles de `para`, hasta que se cierra o pasa `hasta`
// (inclusive). El botón lleva al tema `tema` de la ayuda.
export type BannerNovedad = { para: Rol[], texto: string, corto: string, tema: string, hasta: string }
export type Novedad = { fecha: string, titulo: string, texto: string, para?: Rol[], banner?: BannerNovedad }

export const NOVEDADES: Novedad[] = [
  { fecha: '2026-10-09', titulo: 'Mis jornadas: cargá tus acciones pedagógicas en el formulario de Nivel Central', texto: 'Cada FED tiene ahora Mis jornadas en el menú de las iniciales, con los encuentros de clubes, PEAT, talleres y capacitaciones que creó, uno por fila y con los datos en el orden del formulario para copiar y pegar, con un botón que abre el formulario. Marcá Ya la cargué cuando lo cargues y no se repite: la marca la ven también la coordinación y la administración, y si el encuentro se corrige después, vuelve a pendientes. Si te acompañó alguien, lo carga quien creó la acción. El Reporte de jornadas de la coordinación pasó a ser por encuentro y con las mismas marcas.' },
  { fecha: '2026-10-09', titulo: 'Los avisos de arriba ya no dejan ver el texto de abajo', texto: 'Los avisos celestes de arriba de la agenda (comunicados informativos y novedades) eran algo transparentes y, al desplazar la pantalla, se veía el texto de abajo mezclado con el aviso. Ahora tienen fondo sólido.' },
  { fecha: '2026-10-09', titulo: 'Los avisos de cronogramas indican la localidad', texto: 'En los avisos de cronogramas nuevos y en los recordatorios, cada escuela figura ahora con su localidad (por ejemplo, JI N° 913, Isla Santiago), para distinguir escuelas con el mismo nombre en distintas localidades.', para: ["fed", "ced"] },
  { fecha: '2026-10-09', titulo: 'Calendario y selector de hora en toda la agenda', texto: 'El calendario propio de la agenda (con feriados y recesos marcados) y un selector de hora nuevo, de hora y minutos, ahora se usan en todos los campos de fecha y hora: al registrar o editar una acción y sus encuentros, las licencias y repeticiones, los eventos, los feriados, los comunicados, tu horario DTE y los datos de las escuelas. Ya no se abre el calendario del navegador.' },
  { fecha: '2026-10-09', titulo: 'Reporte de jornadas pedagógicas', texto: 'En el menú de las iniciales hay un Reporte de jornadas para la coordinación y la administración: lista los clubes, PEAT, talleres y capacitaciones con participantes, con los datos en el orden del formulario Registro de Acciones Pedagógicas de Nivel Central para copiarlos uno por uno o todos juntos, el enlace a las fotos de cada fecha y la descarga en Excel.', para: ["ced"] },
  { fecha: '2026-10-09', titulo: 'Calendario de fechas: colores de la agenda y recesos en una sola línea', texto: 'Los feriados y recesos marcados en el calendario de los campos de fecha usan ahora los mismos colores que el calendario de la agenda (rosa para feriados y recesos, lila para aniversarios distritales). Debajo, los días seguidos con el mismo nombre se juntan en una sola línea (por ejemplo, Vacaciones de verano del 4 al 29), así la lista no se alarga.' },
  { fecha: '2026-10-09', titulo: 'El PDF del extracto ya no deja una hoja casi en blanco', texto: 'Cuando la tabla del extracto de cronogramas llenaba la hoja, la nota y el pie quedaban solos en una hoja extra. Ahora la nota va arriba de la tabla, se quitó el pie y la tabla cierra el documento: solo hay una hoja más cuando de verdad hay filas que no entran.', para: ["fed", "ced"] },
  { fecha: '2026-10-09', titulo: 'Feriados y recesos marcados en el calendario', texto: 'Los calendarios de los campos de fecha nuevos (Cronogramas, reclamos y borradores) marcan en magenta los feriados y recesos cargados en la agenda, para todos los distritos (de los distritales se aclara cuál), y listan debajo los del mes que estás viendo. Los sábados y domingos se ven más tenues. Se marcan pero no se bloquean: podés elegir cualquier día.' },
  { fecha: '2026-10-09', titulo: 'Calendario propio en los campos de fecha nuevos', texto: 'Los campos de fecha de Cronogramas (Desde y Hasta), de la fecha y hora de envío del reclamo y de Marcar como enviado ahora abren un calendario con el estilo de la agenda, con las opciones Hoy y Borrar, y se pueden usar con el teclado. Las demás pantallas siguen con el calendario del navegador por ahora.' },
  { fecha: '2026-10-09', titulo: 'Extracto de cronogramas: título y logo de la DTE', texto: 'El PDF del extracto de cronogramas ahora se titula Cronogramas de conectividad y lleva el logo de la Dirección de Tecnología Educativa en el encabezado.', para: ["fed", "ced"] },
  { fecha: '2026-10-09', titulo: 'Extracto de cronogramas para adjuntar', texto: 'En Cronogramas hay un filtro nuevo de fechas (Desde y Hasta) y el botón Extracto para adjuntar, en PDF o Excel: una lista ordenada por fecha con el establecimiento, la tarea, la empresa y el personal a cargo con su DNI, para mandar a jefaturas y escuelas. Toma lo que tenés filtrado y deja afuera lo ya realizado.', para: ["fed", "ced"] },
  { fecha: '2026-10-09', titulo: 'Nuevo reclamo desde el Registro de reclamos', texto: 'En el Registro de reclamos hay un botón Nuevo reclamo para armar uno sin salir de la pantalla. Al cerrar el armado, la lista y tus borradores se actualizan solos.' },
  { fecha: '2026-10-09', titulo: 'Fecha y hora de envío en los reclamos de conectividad', texto: 'El código del asunto (DDMMAAAAHHMM) se arma con la hora del momento en que armás el reclamo. Si lo vas a mandar en otro momento, por ejemplo programado para mañana, ahora podés poner la fecha y la hora de envío en el reclamo armado y el asunto se actualiza. Si ya lo habías guardado en borradores, se actualiza ese mismo borrador.' },
  { fecha: '2026-10-09', titulo: 'Saludo simple y mensajes editables', texto: 'Los mensajes que arma la agenda (reclamos de conectividad y aviso de cronogramas al directivo) abren con un simple Hola y el nombre (por ejemplo, Hola Julio,), sin depender de la hora, así sirven aunque los mandes más tarde o los dejes programados. Además, el texto se puede editar en la misma pantalla antes de copiarlo, abrir el correo o guardarlo en borradores, para que cada uno lo adapte a su estilo.' },
  { fecha: '2026-10-09', titulo: 'Borradores de reclamos de conectividad', texto: 'Si dejás un reclamo programado en el correo o lo vas a mandar después, ahora podés guardarlo en borradores desde el reclamo armado. Cuando salga el mail, lo marcás como enviado desde el Registro de reclamos (Mis borradores), con la fecha en que salió, y recién ahí pasa al registro y se avisa al CED. Los borradores son personales.' },
  { fecha: '2026-10-09', titulo: 'Reclamos de conectividad: establecimientos, jardines y contactos', texto: 'El reclamo ahora habla de "establecimiento" (hay jardines, institutos y CENS, no solo escuelas). Los jardines con piso de PNCE llevan siempre el checklist de predio pequeño (Z3) y no el USAP. Con enlace PBA y piso de PNCE: si el problema es solo del piso, se adjunta el checklist; si es solo del enlace, solo la foto del módem; y si es de los dos (casilla nueva en el formulario), la foto y el checklist. Cuando se adjunta un checklist, el mensaje ya no incluye los datos del contacto (el checklist los pide); cuando va solo la foto del módem, siguen siendo obligatorios, y ahora se precargan desde los contactos de la base (podés elegir otro o editarlos).' },
  { fecha: '2026-10-09', titulo: 'Aviso si no se pueden reprogramar las acciones de una licencia', texto: 'Al cargar una licencia eligiendo reprogramar las acciones planificadas de esos días, si por algún problema no se pudieron reprogramar, el aviso ahora lo dice (antes figuraba como hecho). La licencia queda cargada igual y las acciones se pasan a mano.' },
  { fecha: '2026-10-08', titulo: 'Letra secundaria más grande', texto: 'Los textos secundarios de toda la agenda (fechas, estados, FED, avisos, etiquetas) pasaron de 12 a 13 píxeles para que se lean mejor en el celular, sobre todo al aire libre. El resto de los tamaños no cambió.' },
  { fecha: '2026-10-08', titulo: 'Colores más distinguibles en cuatro acciones', texto: 'Cuatro acciones tenían un color casi igual al de otra y se confundían en el calendario y en los gráficos: Planificación (ahora ciruela), Reunión con Nivel Central (azul profundo), Licencia (marrón) y Entrega de equipamiento (turquesa). El resto de los colores no cambió.' },
  { fecha: '2026-10-08', titulo: 'Comunicados: eliminar los retirados', texto: 'En Comunicados, los que ya están retirados o vencidos tienen un botón Eliminar: lo borra del todo junto con su registro de lecturas. Un comunicado vigente primero se retira.' },
  { fecha: '2026-10-07', titulo: 'Comunicados del CED, con constancia de lectura', texto: 'El CED y la administración pueden mandar comunicados a todos los FED o a algunos: se ven como un banner arriba de la agenda (rojo si es importante, celeste si es informativo) hasta que se marca Leído. El CED ve quién lo leyó y cuándo. Se arman desde el menú de las iniciales, en Comunicados.' },
  { fecha: '2026-10-07', titulo: 'Nueva acción técnica: Relevamiento', texto: 'Al planificar o registrar una visita ya podés elegir Relevamiento, dentro de las acciones Técnicas. Tiene su propio color y suma en los contadores, el Tablero y los informes. Las sub-acciones sugeridas son Equipamiento, Conectividad, Infraestructura eléctrica, Relevamiento de ADM y Relevamiento Institucional (podés escribir otra).' },
  { fecha: '2026-10-07', titulo: 'El buscador funciona igual en toda la agenda', texto: 'La lupa, el selector de escuela, Mis escuelas, el Mapa, Cronogramas, Reclamos y el Tablero ahora buscan con las mismas reglas: sin tildes ni mayúsculas, con sigla y número exactos ("ees 31" no trae la 310), el CUE por el principio y varias palabras en cualquier orden. Antes, algunas pantallas pedían la frase entera en el orden escrito y otras no entendían las siglas.' },
  { fecha: '2026-10-07', titulo: 'Mensaje a la escuela: cierre más simple', texto: 'En Armar mensaje (Cronogramas) el final del texto ya no repite el personal técnico: dice quién estará a cargo de la intervención y pide a la institución que esté al tanto y facilite el ingreso y el acceso a los espacios correspondientes.' },
  { fecha: '2026-10-07', titulo: 'Mensaje a la escuela más claro, con recomendaciones de Conectividad', texto: 'El mensaje de Armar mensaje (Cronogramas) ahora se redacta como los que se mandan por WhatsApp: dice según qué cronograma, cuándo, qué empresa hace qué tarea en la escuela y quién es el personal técnico, y pide facilitar el acceso (y tener accesible el rack en las instalaciones de enlace). Si elegís un contacto con nombre, el saludo lo nombra. En las instalaciones de enlace y de equipo SD-WAN hay un botón nuevo, Copiar recomendaciones, con las aclaraciones de Conectividad para la escuela.' },
  { fecha: '2026-10-07', titulo: 'Colores por tipo de cronograma', texto: 'Cada tipo de cronograma ahora tiene su color: Mantenimiento de piso en azul petróleo, Instalación en turquesa, Reparación de piso en naranja, Enlace y Certificación en índigo, y el resto en gris. Se ve en Cronogramas (con una referencia arriba de la lista), en la ficha de la escuela, en Mis escuelas y en el registro de reclamos.' },
  { fecha: '2026-10-07', titulo: 'Nueva ficha de escuela: más ancha y con bloques desplegables', texto: 'La ficha de la escuela se rediseñó: en la computadora se abre ancha, con dos columnas (Contactos y Ubicación a la izquierda; La escuela y Conectividad a la derecha), una franja con los reclamos abiertos y el cronograma próximo, y los datos principales arriba. Reclamos, Cronogramas, Próximas acciones, Clubes e Historial pasaron a bloques desplegables, cerrados y con su cantidad, que se abren cuando los necesitás. En el celular es la misma ficha, en una columna. Matrícula y secciones ahora están en la tarjeta La escuela.' },
  { fecha: '2026-10-07', titulo: 'Próximos cronogramas en el buscador, la ficha y el mapa', texto: 'Si una escuela tiene un cronograma de conectividad que todavía no terminó, ahora se ve en los resultados de la lupa y del buscador de escuela (Cronograma próximo: tipo y fechas), en un bloque de la ficha de cualquier escuela y en la tarjeta del mapa, sin importar de qué FED sea. El detalle (cómo salió, avisos) sigue en Cronogramas.' },
  { fecha: '2026-10-07', titulo: 'Contactos: correo institucional y correo laboral', texto: 'En Editar datos, los contactos de una escuela distinguen el correo institucional (el de la escuela) del correo laboral (el del directivo), y la lista de contactos indica a cuál corresponde cada uno.' },
  { fecha: '2026-10-07', titulo: 'Cronogramas: avisos con color y predio compartido', texto: 'En Cronogramas, las marcas Escuela avisada (celeste) y Jefatura avisada (violeta) ahora tienen color para que se note de un vistazo a cuáles ya se avisó. Y cada tarjeta indica con qué escuelas comparte predio (con su CUE), para ubicar más fácil los centros de adultos y otras escuelas del mismo edificio; el buscador de la sección también encuentra por esas escuelas.' },
  { fecha: '2026-10-07', titulo: 'Aviso cuando la agenda se actualiza', texto: 'Si tenías la agenda abierta de antes y se publicó una versión nueva, ahora aparece un aviso arriba (La agenda se actualizó) con el botón Actualizar, en lugar de un error técnico al subir un PVE o guardar algo.' },
  { fecha: '2026-10-07', titulo: 'El buscador anterior se retiró', texto: 'El sitio del buscador de escuelas anterior (v0-buscadordte1) ya no funciona: redirige a la agenda. Todo lo que tenía está ahora acá: la lupa (con contactos, conectividad y predio compartido en la ficha), el mapa de la región y Mis escuelas con su Excel, y la edición de datos de las escuelas.' },
  { fecha: '2026-10-07', titulo: 'Reclamos y cronogramas, cruzados', texto: 'En el Registro de reclamos, cada reclamo abierto muestra el cronograma próximo de conectividad de su escuela y, si ya hubo uno posterior al reclamo, te pregunta si se resolvió para que lo marques. Hay un filtro Cronogramas para ver esos reclamos. En Cronogramas, las tarjetas indican si la escuela tiene reclamos abiertos (con un filtro Con reclamo abierto). Es solo una pista: no se cierra nada solo.' },
  { fecha: '2026-10-07', titulo: 'Contactos en la ficha de todas las escuelas', texto: 'La ficha de cualquier escuela (lupa, buscador al agendar, Mis escuelas y mapa) muestra ahora sus contactos, con nombre, cargo, teléfono y correo para llamar o escribir, y el principal primero. Antes solo se veían en las escuelas a cargo y en Mis escuelas.' },
  { fecha: '2026-10-07', titulo: 'Escuelas que comparten predio', texto: 'Cuando varias escuelas funcionan en el mismo edificio, la agenda ahora lo muestra: en los resultados de la lupa y del buscador de escuela aparece Predio N · comparte con… (con el nombre y el CUE de las demás); en la ficha se listan y se abren con un toque; en Mis escuelas llevan la etiqueta Comparte predio con N y el Excel suma las columnas Predio y Comparte predio con; y en el mapa la tarjeta de cada escuela las lista.' },
  { fecha: '2026-10-07', titulo: 'Cambiar la contraseña pide la actual', texto: 'Al cambiar tu contraseña desde el menú de las iniciales, la agenda ahora te pide primero la contraseña actual, además de la nueva y su confirmación, para asegurarse de que sos vos. La nueva tiene que ser distinta de la actual. Con una contraseña temporal no se pide: ahí el cambio es obligatorio.' },
  { fecha: '2026-10-06', titulo: 'Mapa de la región y fichas de las jefaturas', texto: 'En el menú de las iniciales (y en Mis escuelas) hay un Mapa con todas las escuelas y las jefaturas de Región 1: buscá una escuela, filtrá por distrito o por FED y tocá un punto para ver su ficha o cómo llegar. Si una escuela está mal ubicada o no tiene ubicación, el FED a cargo (o el CED) la corrige desde Editar datos, cargando la latitud y la longitud. La ficha de cada escuela suma un mapa chico y su jefatura distrital, con teléfono y correo.' },
  { fecha: '2026-10-06', titulo: 'Conectividad en la ficha de todas las escuelas', texto: 'La ficha de cualquier escuela (buscador y Mis escuelas) muestra ahora su conectividad: enlace, ancho de banda, proveedores, estado PBA, piso tecnológico, ANI y recurso primario, solo con lo que está cargado. El CED y la administración pueden corregirla desde Editar datos, en la solapa Conectividad, y cada cambio queda en el historial.' },
  { fecha: '2026-10-06', titulo: 'Editá los datos de tus escuelas', texto: 'En la ficha de una escuela tuya (buscador o Mis escuelas) aparece Editar datos: podés corregir la dirección, el alias, el nivel, la modalidad, los turnos, la matrícula, las secciones y las observaciones, y agregar, editar o eliminar contactos. Cada cambio queda en el historial de la escuela con tu nombre, y no se avisa a nadie. El nombre, el predio, el distrito, el FED a cargo y otros datos los cambia el CED.' },
  { fecha: '2026-10-06', titulo: 'Excel de Mis escuelas con los próximos cronogramas', texto: 'El Excel de Mis escuelas suma una columna con los próximos cronogramas de cada escuela (la ventana de fechas y el tipo, uno por renglón), para tener todo junto al comparar con tu registro.' },
  { fecha: '2026-10-06', titulo: 'Mis escuelas: buscador grande, lista y Excel', texto: 'En Mis escuelas el buscador pasó al primer plano (con una ✕ para borrar lo escrito) y ahora busca también por dirección y por contacto. Hay una vista en Lista con escuela, CUE, dirección, localidad, distrito y contacto (con teléfono y correo para llamar o escribir), con columnas que se ordenan, además de las tarjetas. El botón Excel descarga la lista tal como la ves, para comparar con tu registro propio.' },
  { fecha: '2026-10-06', titulo: 'Botón Volver en el celular', texto: 'En el celular, Mis escuelas, Cronogramas y el Registro de reclamos tienen arriba un botón Volver que te lleva a la pantalla de la que venías (el Tablero, tu agenda u otra sección), sin pasar por la barra de abajo.' },
  { fecha: '2026-10-06', titulo: 'Accesos rápidos en el Tablero', texto: 'Arriba del Tablero hay tres tarjetas con un número: Mis escuelas (cuántas tenés y cuántas con reclamo abierto), Mis reclamos (abiertos en tus escuelas) y Cronogramas (próximos en tus escuelas). Un toque y entrás directo; siguen estando también en el menú de las iniciales. El CED ve los números de todo el equipo.' },
  { fecha: '2026-10-06', titulo: 'Marcá como resuelto los reclamos de tus escuelas', texto: 'En el registro de reclamos, el FED a cargo de una escuela puede tocar Marcar resuelto en un reclamo abierto, con una nota opcional (por ejemplo, "la escuela confirmó que ya funciona"). No se avisa a nadie y en la tarjeta queda quién lo marcó. El filtro Solo los míos ahora incluye los reclamos de tus escuelas. El CED sigue anotando los números y los demás estados.' },
  { fecha: '2026-10-06', titulo: 'Cronogramas: programa, vigencia y guía para el CED', texto: 'Cada cronograma indica si es de Educar o de PBA y si es una reprogramación. Al abrirlo, Para tener en cuenta muestra la vigencia (de 7 a 10 días desde las fechas), si la escuela tiene turno vespertino y si comparte predio con otra. El CED ve además los pasos de la guía como referencia: contacto de los directivos en PBA (con la fecha límite), domicilio, aviso al establecimiento y estado en la planilla.' },
  { fecha: '2026-10-06', titulo: 'Mensaje a la escuela: solo informa el cronograma', texto: 'El mensaje de Armar mensaje en Cronogramas ahora solo informa el cronograma de conectividad previsto (escuela, tarea, fecha, empresa y responsable), sin pedir cambios de fecha, porque los cronogramas ya vienen establecidos. El responsable sale ordenado (por ejemplo, "Cañete Zenteno") y el DNI va sin puntos.' },
  { fecha: '2026-10-06', titulo: 'Cronogramas: avisá a la escuela con el mensaje armado', texto: 'En cada cronograma, Armar mensaje prepara el aviso informativo para el directivo (tarea, fecha, empresa y responsable) y muestra los contactos de la escuela: lo copiás o lo abrís en tu correo. Después anotás Escuela avisada (el FED a cargo) y, si sos el CED, Jefatura avisada; cuando el CED avisa a la jefatura, el FED recibe una notificación. Hay filtros para ver las visitas con la escuela o la jefatura sin avisar.' },
  { fecha: '2026-10-06', titulo: 'Buscador de escuelas más preciso', texto: 'Al buscar con una sigla y un número, el buscador trae solo lo que pediste: "ees 1" ya no mezcla las técnicas ni las agrarias N° 1, y "ep 4 berisso" suma el distrito para afinar. También entiende más siglas (CENS, CEC, CEF, ISFD, ISFT, EESA y otras). Las extensiones de la escuela pedida salen al final.' },
  { fecha: '2026-10-06', titulo: 'Mis escuelas', texto: 'En el menú de las iniciales, Mis escuelas lista las escuelas que tenés a cargo, con buscador y filtros por distrito y nivel. Cada tarjeta muestra el próximo cronograma, los reclamos abiertos, la próxima acción y la última visita; al tocarla se abre la ficha completa, con conectividad, reclamos, cronogramas y contactos. El CED y la administración ven todas las escuelas, con filtro por FED.' },
  { fecha: '2026-10-06', titulo: 'Cronogramas: anotá cómo salió y recibí avisos', texto: 'En Cronogramas (menú de las iniciales) cada FED ve los cronogramas de sus escuelas y puede anotar si se realizó, no se realizó o se reprogramó (con el motivo); el CED lo ve y recibe un aviso. Cuando aparecen cronogramas nuevos y el día hábil anterior al comienzo, te llega un solo aviso con los de tus escuelas, y el CED recibe un resumen.', banner: { para: ['fed', 'ced'], texto: '¡Novedad! Cronogramas: mirá los de tus escuelas, anotá cómo salieron y recibí avisos agrupados', corto: '¡Novedad! Cronogramas de las escuelas', tema: 'cronogramas', hasta: '2026-10-20' } },
  { fecha: '2026-10-06', titulo: 'Cronogramas en la agenda', texto: 'En el menú de las iniciales, Cronogramas muestra los cronogramas de conectividad de las escuelas (reparaciones, instalaciones, certificaciones), leídos del consolidado de conectividad: ventana de fechas, tipo, proveedor, instaladores y FED a cargo. Se actualiza sola cada madrugada. Por ahora es solo lectura.', para: ['ced'] },
  { fecha: '2026-10-06', titulo: 'Recordatorios de PVE más precisos', texto: 'Si subís tu PVE a la carpeta el mismo día en que sale el recordatorio, la agenda la registra antes de avisar y ya no te llega el aviso de algo que entregaste.', para: ['fed'] },
  { fecha: '2026-10-06', titulo: 'Enlaces de reuniones más fáciles de cargar', texto: 'Al agendar una reunión virtual o híbrida podés pegar la dirección con o sin https://, o todo el texto de la invitación de Meet o Zoom: la agenda toma solo el enlace de la videollamada. Ya no aparece el cartel del navegador "Ingresa una URL".' },
  { fecha: '2026-10-05', titulo: 'Las novedades importantes, en un banner', texto: 'Cuando hay una novedad importante, la agenda la anuncia con un banner celeste arriba de la pantalla, con un botón que te lleva al tema de la ayuda (cada perfil ve la novedad que le corresponde). Se va cuando lo cerrás o a los pocos días, y las novedades siguen en la pestaña Novedades de la ayuda.' },
  { fecha: '2026-10-05', titulo: 'Avisos de reclamos también como banner', texto: 'Cuando un FED registra un reclamo de conectividad, al CED le llega una notificación. Los avisos de reclamos (reclamo nuevo para el CED; número de ticket o resolución para el FED) aparecen además como banner arriba de la pantalla, con el botón Ver registro. Si llegan varios, quedan juntos en un solo banner.' },
  { fecha: '2026-10-04', titulo: 'Agenda del equipo: territorio según la etiqueta', texto: 'En la vista En territorio, la Oficina R1 cuenta siempre (funciona en la EES 31, aunque se cargue con la DTE como sede) y la Asistencia remota nunca cuenta, porque es virtual. En una visita con varias etiquetas alcanza con que una cuente.', para: ['ced'] },
  { fecha: '2026-10-04', titulo: 'Número de encuentro más preciso', texto: 'Al numerar el próximo encuentro de un club o grupo de prácticas, ahora cuentan también las fechas marcadas como realizadas aunque no se hayan completado los datos del encuentro. Si una fecha quedó como realizada sin que hubiera encuentro, pasala a cancelada para que no corra la numeración.', para: ['fed'] },
  { fecha: '2026-10-04', titulo: 'PEAT: la escuela del encuentro a la vista', texto: 'Las tarjetas de los grupos de prácticas muestran, debajo del curso y el grupo, la escuela donde es el encuentro y su localidad. En el detalle, la escuela aparece con su nombre completo, además del CUE.', para: ['fed'] },
  { fecha: '2026-10-03', titulo: 'Contadores del registro de reclamos más parejos', texto: 'En el celular, los tres contadores del registro de reclamos tienen el mismo tamaño y los nombres van en plural: Reclamos enviados, En proceso y Resueltos.' },
  { fecha: '2026-10-02', titulo: 'Buscador de escuela: la lupa en su lugar', texto: 'En el buscador de escuela del reclamo, la lupa ya no se corre al abrir los resultados: queda siempre dentro del campo.' },
  { fecha: '2026-10-02', titulo: 'Reclamos con Gmail directo y menú ordenado', texto: 'En el celular, Abrir en mi correo ahora abre la app de Gmail con el mensaje ya armado, sin pasar por el navegador. Si no tenés la app, se abre en el navegador como antes. Además, el botón Cancelar se ve más claro y el menú de las iniciales quedó agrupado: lo tuyo, conectividad, coordinación (si sos administración) y el resto, con Cerrar sesión al final.' },
  { fecha: '2026-10-02', titulo: 'Estados del registro de reclamos con colores más claros', texto: 'En el registro de reclamos, Reclamo enviado, En proceso y Resuelto ahora se distinguen de un vistazo: ámbar, azul y verde, tanto en los contadores como en cada tarjeta.' },
  { fecha: '2026-10-02', titulo: 'Buscador de escuela en el reclamo', texto: 'Al armar un reclamo de conectividad, los resultados de la búsqueda de la escuela ahora se ven completos en el celular y en la compu, sin cortarse.' },
  { fecha: '2026-10-02', titulo: 'Avisos y Excel en el registro de reclamos', texto: 'Cuando el CED anota el número de ticket o de incidencia de tu reclamo, o lo marca resuelto, te llega una notificación (al tocarla se abre el registro). Además, el botón Excel del registro descarga la lista con tus filtros, con las mismas columnas de la planilla del CED.' },
  { fecha: '2026-10-02', titulo: 'Registro de reclamos de conectividad', texto: 'Al armar un reclamo y mandarlo al CED, tocá Reclamo enviado para registrarlo. En el menú de las iniciales, Registro de reclamos muestra los del equipo con su estado y el número de ticket o de incidencia que anota el CED cuando llega de Nivel Central. Si la escuela ya tiene un reclamo abierto, la agenda te avisa para seguir esa cadena.', banner: { para: ['ced'], texto: '¡Novedad! Los reclamos de conectividad que arman los FED llegan al registro: anotá el número de ticket o de incidencia y marcalos como resueltos desde ahí', corto: '¡Novedad! Reclamos de los FED en el registro', tema: 'registro-reclamos', hasta: '2026-10-19' } },
  { fecha: '2026-10-02', titulo: 'Reclamos de conectividad: mensaje al CED y tu correo oficial', texto: 'El reclamo ahora está redactado para el CED, con el saludo según la hora, el contacto de la escuela con su cargo uno por renglón y sin firma. Se abre en Gmail con tu cuenta institucional y tiene botón Cancelar. Además, el logo y el título de la agenda te llevan siempre al inicio.' },
  { fecha: '2026-10-02', titulo: 'Reclamos de conectividad armados por la agenda', texto: 'Desde el menú de las iniciales, la ficha de una escuela o una acción de Conectividad podés armar el reclamo: la agenda toma el enlace y el piso de la escuela, arma el asunto con el formato de la guía y el cuerpo del mail, y te dice qué adjuntar (checklist, foto del módem, plano). Después lo copiás o lo abrís en Gmail.', banner: { para: ['fed'], texto: '¡Novedad! Ahora podés armar tus reclamos de conectividad desde la agenda', corto: '¡Novedad! Reclamos de conectividad en la agenda', tema: 'reclamos', hasta: '2026-10-19' } },
  { fecha: '2026-10-02', titulo: 'Carpetas de fotos de PEAT con curso y grupo', texto: 'Las carpetas de fotos de los grupos de prácticas se nombran solo con el curso y el grupo, sin la escuela del encuentro. Las existentes se renombran solas en el próximo orden nocturno, o al tocar Ordenar ahora.', para: ['fed'] },
  { fecha: '2026-10-02', titulo: 'PEAT en la agenda: solo curso y grupo', texto: 'Las tarjetas de los grupos de prácticas muestran solo el curso y el grupo (por ejemplo, 7° Informática - Grupo 1), sin la escuela del encuentro. El detalle de la acción sigue indicando dónde fue.', para: ['fed'] },
  { fecha: '2026-10-02', titulo: 'Los grupos de PEAT se identifican por su escuela de origen', texto: 'Un grupo de prácticas ya no queda atado a una sede: se muestra con la escuela de origen de los estudiantes y cada encuentro lleva el lugar donde se hizo. Al crear un grupo nuevo, la escuela de origen es obligatoria.', para: ['fed'] },
  { fecha: '2026-10-02', titulo: 'Informe del período más compacto', texto: 'Los indicadores del informe ocupan menos lugar y el panel se puede plegar con la flecha del título: queda una línea con lo principal y los botones de Excel y PDF a la vista. La app recuerda cómo lo dejaste.' },
  { fecha: '2026-10-02', titulo: 'La cámara solo marca las acciones con fotos', texto: 'Si todas las fotos del día ya quedaron asignadas a otras acciones por horario, las acciones sin fotos dejan de mostrar la cámara. Solo la muestran si quedaron fotos del día sin asignar.', para: ['fed'] },
  { fecha: '2026-10-02', titulo: 'Acceso al sitio DTE Región 1', texto: 'En el menú de las iniciales sumamos Sitio DTE Región 1: abre el sitio de la Dirección en una pestaña nueva, con tu cuenta institucional.' },
  { fecha: '2026-10-01', titulo: 'Buscador de escuelas', texto: 'Con la lupa de arriba buscás cualquier escuela por nombre, sigla o CUE y ves su ficha: datos en tarjetas de color, próximas acciones, clubes y prácticas, y el historial de lo que se hizo ahí. Desde la ficha podés agendar una acción con la escuela ya elegida.' },
  { fecha: '2026-10-01', titulo: 'Más movimiento, siempre suave', texto: 'Los números del tablero suben hasta su valor, las barras crecen, el banner de avisos se desliza al aparecer, la campanita se sacude una vez cuando llega algo nuevo y las pantallas que cargan muestran un brillo suave. Con "reducir movimiento" activado en tu dispositivo, todo aparece quieto.' },
  { fecha: '2026-10-01', titulo: 'Acciones acompañadas en tu informe', texto: 'Tu informe del período muestra aparte las acciones de otros integrantes en las que te etiquetaron y que se realizaron. No se suman a tus totales, no cuentan las que rechazaste y también salen en el Excel y el PDF.' },
  { fecha: '2026-10-01', titulo: 'Los paros se registran como realizados', texto: 'Al agendar un día como Paro queda directamente como realizado, aunque la fecha todavía no haya llegado. Igual podés editarlo. Además, el banner de avisos ahora ocupa menos lugar en el celular.' },
  { fecha: '2026-10-01', titulo: 'Una agenda que se mueve con suavidad', texto: 'Las pantallas y las listas entran con un fundido corto, al marcar una acción como realizada se dibuja una tilde, lo que acabás de guardar se destaca un instante y los desplegables abren y cierran sin saltos. Si tenés activado "reducir movimiento" en tu dispositivo, no se anima nada.' },
  { fecha: '2026-10-01', titulo: 'Ayuda dentro de la agenda', texto: 'Desde el menú de las iniciales › Ayuda encontrás el manual completo, con buscador, siempre al día con la versión de la agenda. Acá mismo vas a ver cada novedad.' },
  { fecha: '2026-10-01', titulo: 'Avisos con color y banner', texto: 'Las notificaciones se distinguen por color (rojo: urgente, amarillo: aviso, verde: confirmación). Lo que pide una acción tuya, como la PVE, aparece además como banner arriba de la pantalla.' },
  { fecha: '2026-10-01', titulo: 'Cargar acciones pasadas no avisa a tus compañeros', texto: 'Al etiquetar o modificar acciones de fechas anteriores a hoy ya no se envía notificación: podés cargar todo junto a fin de mes sin molestar.' },
  { fecha: '2026-10-01', titulo: 'Clubes y talleres más ágiles', texto: 'Propuesta y destinatarios se eligen de una lista, los inscriptos se precargan con los del primer encuentro, el número de encuentro se calcula con los realizados y, al completar los datos de un encuentro, ya no se pregunta por "este y los siguientes".' },
  { fecha: '2026-10-01', titulo: 'Prácticas por curso', texto: 'Si un curso se dividió en grupos, cargá cada grupo en el campo Grupo: en las métricas de prácticas cuenta como un solo curso.', para: ['fed'] },
  { fecha: '2026-10-01', titulo: 'Agenda del equipo: "En territorio"', texto: 'La oficina R1 y las reuniones presenciales dentro de una escuela ahora cuentan como en territorio.', para: ['ced'] },
]

export const ultimaNovedad = (rol: Rol): string | null => NOVEDADES.find(n => !n.para || n.para.includes(rol))?.fecha ?? null

// Id de una novedad con banner (para recordar cuáles se cerraron).
export const idBanner = (n: Pick<Novedad, 'fecha' | 'titulo'>) => `${n.fecha}|${n.titulo}`

// Banner de novedad a mostrar: el de la novedad más reciente con banner para el rol, vigente hoy y que no se cerró.
export function bannerVigente(rol: Rol, hoy: string, cerrados: readonly string[]): { id: string } & BannerNovedad | null {
  const n = NOVEDADES.find(x => x.banner && x.banner.para.includes(rol) && hoy <= x.banner.hasta && !cerrados.includes(idBanner(x)))
  return n?.banner ? { id: idBanner(n), ...n.banner } : null
}
